#!/usr/bin/env bash
# ==============================================================================
# Multisensor docker: one-shot setup for new lab members.
# Run from anywhere: `./scripts/setup.sh` or `bash scripts/setup.sh`.
#
# Idempotent: safe to re-run. Skips work that's already been done.
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$( dirname "${SCRIPT_DIR}" )"
cd "${PROJECT_ROOT}"

# Check if Docker is accessible
if ! docker ps > /dev/null 2>&1; then
    cat <<EOF
ERROR: Docker is not accessible to your user.

  Most likely you're not in the 'docker' group. Fix it:

    sudo usermod -aG docker \$USER
    newgrp docker     # activates immediately in this shell
                      # (or log out and back in to apply everywhere)

  Then verify:
    docker ps

EOF
    exit 1
fi

DOCKER="docker"
COMPOSE="docker compose"

# Check for avahi
if ! systemctl is-active --quiet avahi-daemon; then
    cat <<EOF
   WARNING: avahi-daemon is not running (needed for Ouster .local hostname resolution).
   Fix it with:  sudo systemctl start avahi-daemon
EOF
fi

echo "========================================================================"
echo "  Multisensor Docker — Setup"
echo "  Project root: ${PROJECT_ROOT}"
echo "========================================================================"

# ---- [1/5] .env generation -------------------------------------------------
if [ ! -f ".env" ]; then
    echo "-> [1/5] Generating .env from current host user ($USER, uid=$(id -u))..."
    cat > .env <<EOF
# Auto-generated by scripts/setup.sh — edit freely, will not be overwritten.
USER_NAME=${USER}
USER_UID=$(id -u)
USER_GID=$(id -g)
PLUGDEV_GID=$(getent group plugdev 2>/dev/null | cut -d: -f3 || echo "46")
VIDEO_GID=$(getent group video 2>/dev/null | cut -d: -f3 || echo "44")
DIALOUT_GID=$(getent group dialout 2>/dev/null | cut -d: -f3 || echo "20")

CONTAINER_NAME=multisensor_container

# ROS 2 / DDS
ROS_DOMAIN_ID=0
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
# Path is INSIDE the container; ./config is mounted to /home/${USER}/config
CYCLONEDDS_URI=file:///home/${USER}/config/cyclonedds.xml
EOF
else
    echo "-> [1/5] .env exists, leaving alone."
fi

# Robust env loading — handles spaces, quotes, etc.
set -a
# shellcheck disable=SC1091
source .env
set +a

# ---- [2/5] Ensure directory structure (config might not exist on fresh clone) -
echo "-> [2/5] Ensuring config and sensor_ws directories exists..."
mkdir -p config sensor_ws/src sensor_ws/build sensor_ws/install sensor_ws/log bags maps

# ---- [3/5] vcs import of sensor wrappers -----------------------------------
if [ -f "sensors.repos" ] && [ ! -d "sensor_ws/src/realsense-ros" ]; then
    echo "-> [3/5] Importing sensor wrappers from sensors.repos..."
    if command -v vcs > /dev/null 2>&1; then
        vcs import sensor_ws/src < sensors.repos
    else
        # vcstool isn't on the host — run as root (for apt), then chown to user
        echo "   (vcstool not on host; running inside a temporary container)"
        ${DOCKER} run --rm \
            -v "${PROJECT_ROOT}:/work" \
            -w /work \
            ros:humble-ros-base bash -c \
            "apt-get update -qq && apt-get install -y -qq python3-vcstool > /dev/null && \
            vcs import sensor_ws/src < sensors.repos && \
            chown -R $(id -u):$(id -g) sensor_ws/src"
    fi
else
    echo "-> [3/5] Sensor wrappers already present in sensor_ws/src/, skipping import."
fi

# ---- [4/5] Build (or rebuild) the image ------------------------------------
# We force --build on first run so rosdep bakes from the freshly-imported src.
# Subsequent runs use the cache and are fast.
echo "-> [4/5] Starting container (building image if needed)..."
if [ -z "$(${DOCKER} ps -q -f name=${CONTAINER_NAME})" ]; then
    ${COMPOSE} up -d --build
else
    echo "   Container already running."
fi

# Wait until the container is up and `docker exec` works.
echo -n "   Waiting for container to be ready"
WAIT_DEADLINE=$(( SECONDS + 60 ))
until ${DOCKER} exec "${CONTAINER_NAME}" true > /dev/null 2>&1; do
    if [ "${SECONDS}" -ge "${WAIT_DEADLINE}" ]; then
        echo ""
        echo "ERROR: container did not become ready within 60s."
        echo "       Inspect it with:  ${COMPOSE} logs --tail=50"
        exit 1
    fi
    echo -n "."
    sleep 1
done
echo " ready."

# ---- [5/5] First-time colcon build -----------------------------------------
echo "-> [5/5] Checking workspace build status..."
if ${DOCKER} exec "${CONTAINER_NAME}" \
        test -f "/home/${USER_NAME}/ros2_ws/install/setup.bash"; then
    echo "   Workspace already built. Use 'cb' inside the container to rebuild."
else
    echo "   No install/ found — running first colcon build..."
    ${DOCKER} exec -t -u "${USER_NAME}" "${CONTAINER_NAME}" bash -lc \
        "source /opt/ros/humble/setup.bash && \
         colcon build --symlink-install \
            --cmake-args -Dlibrealsense2_DIR=/usr/local/lib/cmake/realsense2"
fi

echo "========================================================================"
echo "  Setup complete."
echo ""
echo "  Drop into the container with:  ./scripts/shell.sh"
echo "========================================================================"